version: '3.8'

networks:
  front-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

  back-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - back-tier
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: postgres
    networks:
      - back-tier  # Database on back-tier network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  vote:
    build: ./vote
    container_name: vote_app
    networks:
      - front-tier  # Exposed to users
      - back-tier   # Can access Redis and DB
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "${VOTE_PORT}:80"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      DB_HOST: ${DB_HOST}
    restart: unless-stopped

  result:
    build: ./result
    container_name: result_app
    networks:
      - front-tier  # Exposed to users
      - back-tier   # Can access DB
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${RESULT_PORT}:80"
    environment:
      DB_HOST: ${DB_HOST}
    restart: unless-stopped

  worker:
    build: ./worker
    container_name: worker_app
    networks:
      - back-tier   # Can access Redis and DB (no front-tier needed)
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      REDIS_HOST: ${REDIS_HOST}
      DB_HOST: ${DB_HOST}
    restart: unless-stopped

volumes:
  postgres_data:
  jenkins_home:
    external: true 
    name: jenkins_home
